model_config:
  model: UNet1 #the directory to which the results are saved
  initial_filter_size: [64]
  kernel: [3]
  drop_out_rate: [0.4]
  input_size: [800, 800]    #[1536, 1536] #h, w 
  channel: 1
  num_class: 5
  model_type: 'TransUnet' #multi_task, attention, fourier1, fourier1_2, single, TransUnet
  dropout: True
  anydepth: False
train_config:
  train_loss: dice_bce_mc
  val_loss: dice_bce_mc
  optimizer: SGD #SGD
  lr_rate: [0.01]
  adaptive_lr: True
  weight_decay: [0.0001]
  batch_size: [1]
  epochs: 2
  early_stop: 60
  num_workers: 20
  seed: [35]
  use_cuda: True
dataset_config:
  train_path: ['/home/rauzen22/projects/ultrasoundSegmentationDatasetv2_resized/fold1/train']
  val_path: ['/home/rauzen22/projects/ultrasoundSegmentationDatasetv2_resized/fold1/val']
  test_path: ['/home/rauzen22/projects/ultrasoundSegmentationDatasetv2_resized/fold1/test']
  augmentation: False
  save_dir: results
  class_names: ['background','brown', 'red', 'green', 'blue']
resume:
  flag: False
  path: hd_exp1_123_bs/models/last_epoch.pt
  epoch: 75

