dataset: jhu
save_path: save_file/A_ddp
workers: 2
print_freq: 200
start_epoch: 0
epochs: 5000
pre: null
batch_size: 2
crop_size: 256
lr_step: 1200
seed: 1
best_pred: 100000.0
gpu_id: "0,1"
lr: 0.0001
weight_decay: 0.0005
save: false
scale_aug: false
scale_type: 0
scale_p: 0.3
gray_aug: false
gray_p: 0.1
test_patch: false
channel_point: 3
num_patch: 1
min_num: -1
num_knn: 4
test_per_epoch: 20
threshold: 0.35
video_path: ./video_demo/1.mp4
local_rank: -1
lr_backbone: 0.0001
lr_drop: 40
clip_max_norm: 0.1
frozen_weights: null
backbone: resnet50
dilation: false
position_embedding: sine
enc_layers: 6
dec_layers: 6
dim_feedforward: 2048
hidden_dim: 256
dropout: 0.1
nheads: 8
num_queries: 2000
pre_norm: false
masks: false
aux_loss: true
set_cost_class: 2
set_cost_point: 5
set_cost_giou: 2
mask_loss_coef: 1
dice_loss_coef: 1
cls_loss_coef: 2
count_loss_coef: 2
point_loss_coef: 5
giou_loss_coef: 2
focal_alpha: 0.25
dataset_file: crowd_data
coco_path: null
coco_panoptic_path: null
remove_difficult: false
output_dir: ""
device: cuda
resume: ""
eval: false
num_workers: 2
world_size: 1
dist_url: "env:// "
master_port: 29501
distributed: false

